# Generated by Django 2.2 on 2019-04-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='Balance',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='balance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
